config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :boards, shallow: true do
    resources :cards do
      collection do
        get :get_children
      end
      resources :tasks
    end
    get 'tasks/change', to: 'tasks#change'

  end

  resources :users, only: [:index, :show, :edit] do 
    collection do
      post :add
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :home, only: [:new, :index]

  get '/logout', to: 'home#logout', as: 'logout'

  resources :organisations do
  	  collection do
    	get 'plan_choice'
    	patch 'subscribed'
      get 'alter'
  	  end
  end


  resources :subscriptions do
  	collection do 
  		get :details
      get :calculate
    end
  end


  namespace :api do
    namespace :v1 do
      resources :users
      resources :projects
      # resources :projects, only: [:index] do
      #   collection do
      #     get 'import'
      #   end
      # end
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :board

  belongs_to :parent, :class_name => "Card", :foreign_key => "parent_id", optional: true
  has_many :children, :class_name => "Card", :foreign_key => "parent_id"
  has_many :tasks
  validates_length_of :title,  maximum: 288, presence: true


  def tasks_completed?
  	self.tasks.size == self.tasks.completed_are.size 
  end

  def self.competed_cards
  	self.all.reject{|card| card unless card.tasks_completed? && !card.tasks.blank? }
  end

  def self.uncompleted_cards 
  	self.all.reject{|card| card unless !card.tasks_completed? && !card.tasks.blank? }
  end

end

app/models/task.rb
class Task < ApplicationRecord
	default_scope -> { order(:id) } 

	validates_length_of :title,  maximum: 288, presence: true
	belongs_to :card

	def self.completed_are
		self.where(completed: true)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_card, only: [:index, :new, :create]

  def index
    @tasks = @card.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = @card.tasks.new(task_params)
    
    respond_to do |format|
      if @task.save
          format.html {redirect_to board_cards_url(@card.board) , notice: 'Task was successfully created.' }
        else
          format.html { render :new }
        end
      end 
  end

  def show
  end

  def edit
  end

  def update
  end

  def change
    @task = Task.find(params[:id])
    @task.update(completed: params[:completed])
    @card = @task.card
    card_report
  end

  private

  def set_card
    @card = Card.find(params[:card_id])
  end

    def task_params
      params.require(:task).permit( :title, :card_id)
    end

    def card_report
      @board = @card.board
      @completed_cards = @board.cards.competed_cards
      @uncompleted_cards = @board.cards.uncompleted_cards
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="container">
<%= form_for [@card, @task] do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class => "form-control" %>
</div>

  <div class="form-group">
    <%= form.submit "Create",  :class => 'btn btn-info' %>
  </div>
</div>
<% end %>
</div>

app/views/tasks/_tasks.html.erb
			    <div class="modal-dialog">
			    
			      <!-- Modal content-->
			      <div class="modal-content">
			        <div class="modal-header">
			          <button type="button" class="close" onclick="close_modal()">&times;</button>
			          <h4 class="modal-title">Tasks of <%=@card.title%></h4>
			        </div>
			        <div class="modal-body">
			          <table class="table table-hover" data-card="<%=@card.id%>">
			          	<thead>
			          		<tr>
  			

			          			<th colspan="2">
			          				<%= link_to new_card_task_url(@card) do %>
			          					<span class="btn btn-primary">Add New Task</span>
			          				<%end%>
			          			</th>
			          		</tr>
			          		<tr>
			          			<th id="message"></th>
			          		</tr>
			          	</thead>
			          	<tbody>
			          		<% @tasks.each do |task| %>
			          			<tr>
			          				<td><%=task.title%></td>
			          				<td><%= check_box_tag 'task_ids[]', task.id , task.completed%></td>
			          			</tr>
			          		<%end%>
			          	</tbody>
			          </table>
			        </div>
			        <div class="modal-footer">
			          <button type="button" class="btn btn-default" onclick="close_modal()">Close</button>
			        </div>
			      </div>
			      
			    </div>

app/views/tasks/change.js.erb
$('#card_<%=@card.id%>').css("border-color", "<%=border_color(@card)%>" )
$("#card_report").html("<%= escape_javascript(render('cards/card_report')) %>")

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.js.erb
$('#Modal_<%=@card.id%>').show()
$('#Modal_<%=@card.id%>').html("<%= escape_javascript(render('tasks')) %>")

$('input[name="task_ids[]"]').change(function(){

	var task = $(this).val()
	var completed = this.checked
	

        
		$.ajax({
		  url: "tasks/change",
		  type: "get",
		  data: {id: task, completed: completed}, //send it through get method
		  success: function(response) {
		    //Do Something
		  },
		  error: function(xhr) {
		    //Do Something to handle error
		  }
		});		
			

 });

app/views/tasks/new.html.erb
<div class="container">
<h1>New Task of <%=@card.title%></h1>

	<%= render 'form', task: @task %>
	<div class="col">
	<%= link_to 'Back', board_cards_path(@card.board) %>
	</div>
</div>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>