config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :boards, shallow: true do
    resources :cards do
      collection do
        get :get_children
      end
      resources :tasks
    end
    get 'tasks/change', to: 'tasks#change'

  end

  resources :users, only: [:index, :show, :edit] do 
    collection do
      post :add
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :home, only: [:new, :index]

  get '/logout', to: 'home#logout', as: 'logout'

  resources :organisations do
  	  collection do
    	get 'plan_choice'
    	patch 'subscribed'
      get 'alter'
  	  end
  end


  resources :subscriptions do
  	collection do 
  		get :details
      get :calculate
    end
  end


  namespace :api do
    namespace :v1 do
      resources :users
      resources :projects
      # resources :projects, only: [:index] do
      #   collection do
      #     get 'import'
      #   end
      # end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  belongs_to :organisation, optional: true

def self.new_with_session(params, session)
	super.tap do |user|
		if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
		user.email = data["email"] if user.email.blank?
		end
	end
end

def self.from_omniauth(auth)
	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		user.email = auth.info.email
		user.password = Devise.friendly_token[0,20]
		user.name = auth.info.name # assuming the user model has a name
		user.image = auth.info.image # assuming the user model has an image
	end
end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_admin_user
  before_action :check_org

  def index 
    @users = current_user.organisation.users
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def add
    if users_within_limit?
      params[:organisation_id] = current_user.organisation_id
      params[:normal_user] = true
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to '/users'
    end
  end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.permit(:name, :email, :password, :normal_user, :organisation_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form-inline">
	<%= form_tag add_users_path do %>
	
	<div class="form-group">
	  <%= text_field_tag :email,  %>
	</div>
	
	<div class="form-group">
	  <%= text_field_tag :password, :class => "form-control" %>
	</div>
	 
	 <div class="form-group">
	  <%= submit_tag "Add"%>
	</div>
	
	</div>
	<% end %>
</div>	

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Email</th>
        <th></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <%unless current_user.id == user.id %>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%else%>
          <td style="color: red"><b>Admin</b></td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <% if !current_user.normal_user && users_within_limit? %>
    <%= form_tag add_users_path, :class => "form-inline" do %>
    <div class="form-group">
      <label> Email</label> &nbsp;
      <%= text_field_tag :email, "", class: "form-control" %>
    </div>

    <div class="form-group">
      &nbsp;&nbsp;<label>Password</label> &nbsp;
      <%= text_field_tag :password, "", class: "form-control" %>
    </div>&nbsp;&nbsp;
      <%= submit_tag "Add New User", :class => "btn btn-info" %>
    <% end %>
  <% end %>
<br>
<%= link_to 'Back To Home', home_index_path %>

  <br>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>


<p>
  <strong>Organisation:</strong>
  <%= @user.organisation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>