config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :boards, shallow: true do
    resources :cards do
      collection do
        get :get_children
      end
      resources :tasks
    end
    get 'tasks/change', to: 'tasks#change'

  end

  resources :users, only: [:index, :show, :edit] do 
    collection do
      post :add
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :home, only: [:new, :index]

  get '/logout', to: 'home#logout', as: 'logout'

  resources :organisations do
  	  collection do
    	get 'plan_choice'
    	patch 'subscribed'
      get 'alter'
  	  end
  end


  resources :subscriptions do
  	collection do 
  		get :details
      get :calculate
    end
  end


  namespace :api do
    namespace :v1 do
      resources :users
      resources :projects
      # resources :projects, only: [:index] do
      #   collection do
      #     get 'import'
      #   end
      # end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "setup", only: [:new]
	before_action :check_org

	def index
		#@user = User.find(session[:user_id])
	end

	def new
	end

	def login
		
	end

	def logout
    	session[:user_id] = nil         
    	redirect_to new_home_path
    end 

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">

  <br/>
  <div class="row">
    <%= link_to boards_path, html_options = {:class => "btn btn-success col-sm-4"} do %>
      <p style="height: 100px;padding: 50px;">
        Boards
      </p>
    <%end%>
    <div class="col-sm-1"></div>
    <% if !current_user.normal_user %>

    <%= link_to users_path, html_options = {:class => "btn btn-info col-sm-4"} do %>
      <p style="height: 100px;padding: 50px;">
        Users
      </p>
    <%end%>
    <%end%>

  </div>


</div>

app/views/home/new.html.erb
    <div class="container">
        <div class="row text-center ">
            <div class="col-md-12">
                <br /><br />
                <h2>Login</h2>

                <h5>( Login yourself to get access )</h5>
                 <br />
            </div>
        </div>
         <div class="row ">

                  <div class="col-md-12 ">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                        <strong>   Enter Details To Login </strong>
                            </div>
                            <div class="panel-body">
                                <%#= form_with(model: user, local: true) do |form| %>

                                       <br />
                                     <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-tag"  ></i></span>
                                            <input type="text" class="form-control" placeholder="Your Username" name="username" />
                                        </div>
                                                                              <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-lock"  ></i></span>
                                            <input type="password" class="form-control" placeholder="Your Password" name="password" />
                                        </div>
                                    <div class="form-group">


                                        </div>

                                     <input type="submit" name="login" class="btn btn-primary " value="Login Now" />
                                    

      
        <%= link_to 'Sing Up', new_organisation_path, class: 'btn btn-info' %>
     
<% if user_signed_in? %>
  <%= link_to "Edit profile", edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path  %> |
  <%= link_to "Login", new_user_session_path  %>
<% end %>
                                    <%#end%>