config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :boards, shallow: true do
    resources :cards do
      collection do
        get :get_children
      end
      resources :tasks
    end
    get 'tasks/change', to: 'tasks#change'

  end

  resources :users, only: [:index, :show, :edit] do 
    collection do
      post :add
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :home, only: [:new, :index]

  get '/logout', to: 'home#logout', as: 'logout'

  resources :organisations do
  	  collection do
    	get 'plan_choice'
    	patch 'subscribed'
      get 'alter'
  	  end
  end


  resources :subscriptions do
  	collection do 
  		get :details
      get :calculate
    end
  end


  namespace :api do
    namespace :v1 do
      resources :users
      resources :projects
      # resources :projects, only: [:index] do
      #   collection do
      #     get 'import'
      #   end
      # end
    end
  end

end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :organisation
  belongs_to :user
  has_many :cards, dependent: :destroy

  def self.organisation_is organisation_id
  	self.where(organisation_id: organisation_id)
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_board, only: [:show, :edit, :destroy]
  before_action :add_user_id_and_organisation_id_into_params, only: [:create]
  before_action :check_limit, only: [:create, :new]


  def index
    @boards = Board.organisation_is(current_user.organisation_id)
  end


  def show
  end

  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to boards_url, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to boards_url, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def canvas
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:title, :organisation_id, :user_id)
    end

    def add_user_id_and_organisation_id_into_params
       params[:board][:user_id] = current_user.id
       params[:board][:organisation_id] = current_user.organisation.id      
    end

    def check_limit
      redirect_to boards_url unless boards_within_limit?
    end


end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class => "form-control" %>
  </div>


  <div class="form-group">
  <% if boards_within_limit? %>
    <%= form.submit "Create" , :class => "btn btn-info btn-block" %>
  <%end%>
  </div>
<% end %>

app/views/boards/edit.html.erb
<div class="container">
	<h1>Editing Board</h1>

	<%= render 'form', board: @board %>

	<%= link_to 'Show', @board %> |
	<%= link_to 'Back', boards_path %>
</div>

app/views/boards/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<br>
<% if boards_within_limit? %>
  <%= link_to 'New Board', new_board_path %>
<%end%>
<h1>Boards</h1>

 <div class="row">

 
    <% @boards.each do |board| %>
   <div class="col-sm-3 board" >
        <p><%= board.title %></p>
        <p><%= board.organisation.name %></p>
        <p><%= board.user.email %></p>
        <p>
        <%= link_to 'Open' , board_cards_path(board) %>
        <%= link_to 'Show', board %>
        <%= link_to 'Edit', edit_board_path(board) %>
        <%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
    <% end %>
 </div>


</div>

app/views/boards/new.html.erb
<div class="container">
	<h1>New Board</h1>

	<%= render 'form', board: @board %>

	<%= link_to 'Back', boards_path %>
</div>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>


<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>